<?php
    $childHtml = $block->getChildHtml();
?>

<div class="<?= $block->getCssClass() ?>">
    <a class="action toggle switcher-trigger"
        href="<?= $block->escapeUrl($block->getHref()) ?>"
        title="<?= $block->escapeHtml($block->getTitle()) ?>"
        <?php if ($childHtml) : ?>
            data-mage-init='<?php echo $this->getJsonConfig() ?>'
            data-toggle="dropdown"
            data-trigger-keypress-button="true"
        <?php endif ?>
    >
        <?php if ($block->getIcon()) : ?>
            <?= $block->getIcon() ?>
            <span class="abs-visually-hidden"><?= $block->escapeHtml($block->getTitle()) ?></span>
        <?php else : ?>
            <?= $block->escapeHtml($block->getTitle()) ?>
        <?php endif ?>
    </a>

    <?php if ($childHtml) : ?>
        <div class="dropdown switcher-dropdown" data-target="dropdown">
            <?= $childHtml ?>
        </div>
    <?php endif ?>
</div>
