<?php
    $childHtml = $block->getChildHtml();
    $srOnly = $block->getSrOnly();
?>

<div class="switcher">
    <?php if ($block->getLabel()) : ?>
        <strong class="label switcher-label">
            <span><?= $block->escapeHtml($block->getLabel()) ?></span>
        </strong>
    <?php endif ?>

    <div class="<?= $block->getCssClass() ?>">
        <a class="action toggle switcher-trigger"
            href="<?= $block->escapeUrl($block->getHref()) ?>"
            title="<?= $block->escapeHtml($block->getTitle()) ?>"
            <?php if ($childHtml) : ?>
                data-mage-init='<?php echo $this->getJsonConfig() ?>'
                data-toggle="dropdown"
                data-trigger-keypress-button="true"
            <?php endif ?>
        >
            <?php if ($block->getIcon()) : ?>
                <?php $srOnly = true ?>
                <?= $block->getIcon() ?>
            <?php endif ?>

            <strong class="<?= $srOnly ? 'abs-visually-hidden' : '' ?>">
                <span><?= $block->escapeHtml($block->getTitle()) ?></span>
            </strong>
        </a>

        <?php if ($childHtml) : ?>
            <div class="dropdown switcher-dropdown" data-target="dropdown">
                <?= $childHtml ?>
            </div>
        <?php endif ?>
    </div>
</div>
