<style>
@media (prefers-reduced-motion: no-preference) {
    <?= $block->getCssSelector() ?> {
        opacity: 0;
        visibility: hidden;
    }
}
</style>
<script>
require(['jquery', 'underscore'], ($, _) => {
    var selector = <?= $block->getJsSelector() ?>,
        containers = [
            '.scroll-reveal-cascade',
            '.scroll-reveal-container',
            '[data-content-type="html"], [data-content-type="row"], .columns, body',
        ];

    $.async(selector, _.debounce(() => {
        $(selector).filter(':not(.reveal-ready)').onReveal(items => {
            var counter = 0, prevContainer;

            items.each((i, el) => {
                    containers.some(selector => {
                        var parent = $(el).closest(selector).get(0);

                        if (parent) {
                            if (parent !== prevContainer) {
                                prevContainer = parent;
                                counter = 0;
                            }
                            return true;
                        }
                    });

                    $(el).var('--animation-order', counter++);
                })
                .addClass('scroll-reveal reveal-slide-in reveal-ready');
        });
    }, 40));
});
</script>
