<?php if ($block->getLayout()->getBlock('breeze.viewTransition')?->getEnabled()) : ?>
<style id="breeze-view-transition">
    @view-transition {
        navigation: auto;
    }
</style>
<script>
    if (/FBAN|FBAV|Instagram/i.test(navigator.userAgent) && /Android/i.test(navigator.userAgent)) {
        document.querySelector('#breeze-view-transition')?.remove();
    }
</script>
<?php endif ?>

<script type="speculationrules">
{
    "prerender": [{
        "eagerness": "moderate",
        "source": "document",
        "where": {
            "and": [
                { "href_matches": "/*" },
                { "not": {
                    "href_matches": [
                        "**/checkout/*",
                        "**/customer/*",
                        "**/download/*",
                        "**/redirect/*",
                        "**/sales/*",
                        "**/wishlist/*",
                        "*.pdf"
                    ]
                }},
                { "not": {
                    "selector_matches": [
                        ".do-not-prerender",
                        "[data-post]",
                        "[rel~=nofollow]"
                    ]
                }}
            ]
        }
    }]
}
</script>
