<?php if ($block->getLayout()->getBlock('breeze.viewTransition')?->getEnabled()) : ?>
<style id="breeze-view-transition">
@media (prefers-reduced-motion: no-preference) {
    @view-transition {
        navigation: auto;
    }
}
</style>
<script>
    if (/FBAN|FBAV|Instagram/i.test(navigator.userAgent) && /Android/i.test(navigator.userAgent)) {
        document.querySelector('#breeze-view-transition')?.remove();
    }
</script>
<?php endif ?>

<?php
    $urlPrefix = (string) parse_url($block->getBaseUrl(), PHP_URL_PATH);
    $urlPrefix = rtrim($urlPrefix, '/');
    $excludePaths = [
        'checkout',
        'customer',
        'download',
        'stores/store/redirect',
        'sales',
        'wishlist'
    ];
    foreach ($excludePaths as $i => $path) {
        $excludePaths[$i] = $urlPrefix . '/' . $path . '/*';
    }
    $excludePaths[] = '*.pdf';
?>

<script type="speculationrules">
{
    "prerender": [{
        "eagerness": "moderate",
        "source": "document",
        "where": {
            "and": [
                { "href_matches": "/*" },
                { "not": {
                    "href_matches": <?= /* @noEscape */ json_encode($excludePaths, JSON_HEX_TAG | JSON_UNESCAPED_SLASHES) ?>
                }},
                { "not": {
                    "selector_matches": [
                        ".do-not-prerender",
                        "[data-post]",
                        "[rel~=nofollow]"
                    ]
                }}
            ]
        }
    }]
}
</script>
