<div class="field">
    <label class="label" for="estimate_<?= $block->escapeHtmlAttr($block->getName()) ?>"><span><?= $block->escapeHtml($block->getLabel()) ?></span></label>
    <div class="control">
        <?php if ($block->getOptions()): ?>
            <select class="select" name="<?= $block->escapeHtmlAttr($block->getName()) ?>" id="estimate_<?= $block->escapeHtmlAttr($block->getName()) ?>">
                <?php foreach ($block->getOptions() as $option): ?>
                    <option value="<?= $option['value'] ?? '' ?>"><?= $option['label'] ?? '' ?></option>
                <?php endforeach ?>
           </select>
        <?php else: ?>
            <input type="text" class="input-text" name="<?= $block->escapeHtmlAttr($block->getName()) ?>" id="estimate_<?= $block->escapeHtmlAttr($block->getName()) ?>">
        <?php endif ?>
    </div>
</div>
