<?php
/** @var \Magento\Checkout\Block\Cart\Sidebar $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
        data-bind="scope: 'minicart_content'">
        <span class="text empty" data-bind="
            css: {
                empty: !!getCartParam('summary_count') == false
            }"
        ><?= $block->escapeHtml(__('My Cart')) ?></span>
        <span class="counter qty empty"
            data-bind="
                css: {
                    empty: !!getCartParam('summary_count') == false && !isLoading()
                },
                blockLoader: isLoading
        ">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko if: getCartParam('summary_count') > 1 --><span><?= $block->escapeHtml(__('items')) ?></span><!-- /ko -->
                <!-- ko if: getCartParam('summary_count') === 1 --><span><?= $block->escapeHtml(__('item')) ?></span><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()):?>
        <div class="block block-minicart"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="
                scope: 'minicart_content'
            "><!-- ko template: { if: shouldRender, name: getTemplate() } --><!-- /ko --></div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php endif ?>

    <?php if (isset($secureRenderer)) : ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], 'window.checkout = ' .
         /* @noEscape */ $block->getSerializedConfig(), false); ?>
    <?php else: ?>
        <script>
            window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
        </script>
    <?php endif ?>

    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
</div>
