<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && !$mainImage) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageUrl = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

$mainImageLabel = $block->getProduct()->getName();
if ($mainImage && $mainImage->getLabel()) {
    $mainImageLabel = $mainImage->getLabel();
}

$width = (int) $block->getImageAttribute('product_page_image_medium', 'width');
$height = (int) $block->getImageAttribute('product_page_image_medium', 'height');
$height = $height ?: $width;
$thumbWidth = (int) $block->getImageAttribute('product_page_image_small', 'width');
$thumbHeight = (int) $block->getImageAttribute('product_page_image_small', 'height');
$thumbHeight = $thumbHeight ?: $thumbWidth;

$mode = $block->getGalleryOptions()->getVar('gallery/mode');
$navType = $block->getGalleryOptions()->getVar('gallery/nav');
$navDir = $block->getGalleryOptions()->getVar('gallery/navdir');
$showCaption = $block->getGalleryOptions()->getVar('gallery/caption');

$responsiveImageHelper = $this->helper(\Swissup\Breeze\Helper\Image::class);
$srcset = $responsiveImageHelper->getSrcset($block->getProduct(), 'product_page_image_medium');
$sizes = $responsiveImageHelper->getSizes('product_page_image_medium');
$thumbSizes = $responsiveImageHelper->getSizes('product_page_image_small');

$galleryId = 'gallery-' . $block->getProduct()->getId();
?>

<div class="breeze-gallery <?= $block->escapeHtmlAttr($mode) ?> <?= $block->escapeHtmlAttr($navDir) ?> <?= $showCaption ? 'caption' : '' ?>">
    <div class="stage <?= $mainImage && $mainImage->getVideoUrl() ? 'video' : '' ?>"
        data-gallery-id="<?= $galleryId ?>"
        data-gallery-role="gallery-placeholder"
        data-caption="<?= $block->escapeHtmlAttr($mainImageLabel) ?>">
        <div class="main-image-wrapper">
            <img alt="<?= $block->escapeHtmlAttr($mainImageLabel) ?>"
                fetchpriority="high"
                class="main-image"
                src="<?= $block->escapeUrl($mainImageUrl) ?>"
                width="<?= $width ?>"
                height="<?= $height ?>"
                <?php if ($srcset) : ?>
                    srcset="<?= $block->escapeHtmlAttr($srcset) ?>"
                    sizes="<?= $block->escapeHtmlAttr($sizes) ?>"
                <?php endif ?>
            />
        </div>

        <?php if (count($images) > 1) : ?>
            <a href="#" class="prev" tabindex="-1" aria-label="<?= __('Previous Image') ?>">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                </svg>
            </a>
            <a href="#" class="next" tabindex="-1" aria-label="<?= __('Next Image') ?>">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                </svg>
            </a>
        <?php endif ?>

        <div class="controls">
            <a href="#" class="zoom zoom-in">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
                </svg>
            </a>
            <a href="#" class="zoom zoom-out">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M20 12H4" />
                </svg>
            </a>
        </div>

        <a href="#" class="close">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
        </a>
    </div>

    <?php if ($mode === 'expanded') : ?>
        <div class="images">
            <?php $i = 0; foreach ($images as $image) : ?>
                <?php
                    $lazy = (bool) $i++;
                    $classes = array_filter([
                        'item',
                        $image->getVideoUrl() ? 'video' : ''
                    ]);

                    $srcset = $responsiveImageHelper->getSrcset($image, 'product_page_image_medium');
                ?>
                <a class="<?= implode(' ', $classes) ?>"
                    href="<?= $block->escapeUrl($image->getLargeImageUrl()) ?>"
                    title="<?= $block->escapeHtmlAttr($image->getLabel() ?: __('View Image')) ?>"
                    data-caption="<?= $block->escapeHtmlAttr($image->getLabel() ?: $block->getProduct()->getName()) ?>">
                    <img <?= $lazy ? 'loading="lazy"' : '' ?>
                        alt="<?= $block->escapeHtmlAttr($image->getLabel()) ?>"
                        src="<?= $block->escapeUrl($image->getMediumImageUrl()) ?>"
                        <?php if ($srcset) : ?>
                            srcset="<?= $block->escapeHtmlAttr($srcset) ?>"
                            sizes="<?= $block->escapeHtmlAttr($sizes) ?>"
                        <?php endif ?>
                        width="<?= $width ?>"
                        height="<?= $height ?>"/>
                </a>
            <?php endforeach ?>
        </div>
    <?php endif ?>

    <div class="thumbnails <?= $navType ?: 'hidden' ?>">
        <?php if (count($images) > 1) : // empty parent wrapper may be used at configurable product page ?>
            <?php foreach ($images as $image) : ?>
                <?php
                    $classes = array_filter([
                        'item',
                        $block->isMainImage($image) ? 'active' : '',
                        $image->getVideoUrl() ? 'video' : ''
                    ]);

                    $srcset = $responsiveImageHelper->getSrcset($image, 'product_page_image_small');
                ?>
                <a class="<?= implode(' ', $classes) ?>"
                    href="<?= $block->escapeUrl($image->getLargeImageUrl()) ?>"
                    title="<?= $block->escapeHtmlAttr($image->getLabel() ?: __('View Image')) ?>">
                    <img loading="lazy"
                        alt="<?= $block->escapeHtmlAttr($image->getLabel()) ?>"
                        src="<?= $block->escapeUrl($image->getSmallImageUrl()) ?>"
                        <?php if ($srcset) : ?>
                            srcset="<?= $block->escapeHtmlAttr($srcset) ?>"
                            sizes="<?= $block->escapeHtmlAttr($thumbSizes) ?>"
                        <?php endif ?>
                        width="<?= $thumbWidth ?>"
                        height="<?= $thumbHeight ?>"
                    />
                </a>
            <?php endforeach ?>
        <?php endif ?>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-id='<?= $galleryId ?>']": {
            "mage/gallery/gallery": {
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>
            }
        }
    }
</script>

<?php if ($mode === 'expanded') : ?>
    <script type="text/x-magento-template" id="gallery-image">
        <a class="<%- classes %>" href="<%- full %>" data-caption="<%- caption %>">
            <img loading="lazy" alt="<%- caption %>"
                src="<%- img %>"
                srcset="<%- srcset ? srcset.medium : '' %>"
                sizes="<?= $sizes ?>"
                width="<?= $width ?>"
                height="<?= $height ?>"
            />
        </a>
    </script>
<?php endif ?>

<script type="text/x-magento-template" id="gallery-thumbnail">
    <a class="<%- classes %>" href="<%- full %>">
        <img loading="lazy" alt="<%- caption %>"
            src="<%- thumb %>"
            srcset="<%- srcset ? srcset.small : '' %>"
            sizes="<?= $thumbSizes ?>"
            width="<?= $thumbWidth ?>"
            height="<?= $thumbHeight ?>"
        />
    </a>
</script>
