<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageUrl = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

$width = (int) $block->getImageAttribute('product_page_image_medium', 'width');
$height = (int) $block->getImageAttribute('product_page_image_medium', 'height');
$height = $height ?: $width;
$thumbWidth = (int) $block->getImageAttribute('product_page_image_small', 'width');
$thumbHeight = (int) $block->getImageAttribute('product_page_image_small', 'height');
$thumbHeight = $thumbHeight ?: $thumbWidth;

?>

<div class="breeze-gallery <?= $block->getGalleryOptions()->getVar('gallery/navdir') ?>" tabindex="0">
    <div class="stage <?= $mainImage && $mainImage->getVideoUrl() ? 'video' : '' ?>"
        data-gallery-role="gallery-placeholder">
        <div class="main-image-wrapper">
            <img loading="lazy" alt="<?= $mainImage ? $mainImage->getLabel() : '' ?>"
                class="main-image"
                src="<?= $mainImageUrl ?>"
                width="<?= $width ?>"
                height="<?= $height ?>"
            />
        </div>

        <?php if (count($images) > 1) : ?>
            <a href="#" class="prev">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                </svg>
            </a>
            <a href="#" class="next">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                </svg>
            </a>
        <?php endif ?>
    </div>

    <?php if (count($images) > 1) : ?>
        <div class="thumbnails">
        <?php foreach ($images as $image) : ?>
            <?php
                $classes = array_filter([
                    'item',
                    $block->isMainImage($image) ? 'active' : '',
                    $image->getVideoUrl() ? 'video' : ''
                ]);
            ?>
            <a class="<?= implode(' ', $classes) ?>" href="<?= $image->getLargeImageUrl() ?>">
                <img loading="lazy" alt="<?= $image->getLabel() ?>"
                    src="<?= $image->getSmallImageUrl() ?>"
                    width="<?= $thumbWidth ?>"
                    height="<?= $thumbHeight ?>"
                />
            </a>
        <?php endforeach ?>
        </div>
    <?php endif ?>

    <a href="#" class="close">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
    </a>
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>
            }
        }
    }
</script>
