<script data-breeze>
    var customerDataConfig = {
        "sectionLoadUrl": "<?= $block->escapeJs($block->getCustomerDataUrl('customer/section/load')) ?>",
        "expirableSectionLifetime": <?= (int)$block->getExpirableSectionLifetime() ?>,
        "expirableSectionNames": <?= /* @noEscape */ $this->helper(\Magento\Framework\Json\Helper\Data::class)
            ->jsonEncode($block->getExpirableSectionNames()) ?>,
        "cookieLifeTime": "<?= $block->escapeJs($block->getCookieLifeTime()) ?>",
        "updateSessionUrl": "<?= $block->escapeJs(
            $block->getCustomerDataUrl('customer/account/updateSession')
        ) ?>"
    }
</script>
