<?php

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$scriptString = <<<script

    require(
        [
            'jquery'
        ],
        function($) {
            $(function() {
                window.print();
            });
        }
    );

script;

if (isset($secureRenderer)) {
    echo $secureRenderer->renderTag('script', [], $scriptString, false);
} else {
    echo "<script>{$scriptString}</script>";
}
