<?php

/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter
 */

$localeString = '';
if (isset($localeFormatter)) {
    $localeString = "var LOCALE = '{$block->escapeJs($localeFormatter->getLocaleJs())}';";
}

$scriptString = <<<script

    {$localeString}
    var BASE_URL = '{$block->escapeJs($block->getBaseUrl())}';
    var VIEW_URL = '{$block->escapeJs($block->getViewFileUrl("/"))}';
    var required = [];
    var require = (deps, callback) => required.push([deps, callback]);

script;

echo /* @noEscape */ $secureRenderer->renderTag('script', ['data-breeze' => true], $scriptString, false);
