<?php /** @var $block \Magento\Checkout\Block\Cart\Shipping */

// print_r(json_decode($block->getJsLayout(), true)['components']['checkoutProvider']['dictionaries']);
// die;

$title = $block->escapeHtml(__('Estimate Shipping and Tax'));
$note = $block->escapeHtml(__('Enter your destination to get a shipping estimate.'));

if ($block->getQuote()->isVirtual()) {
    $title = $block->escapeHtml(__('Estimate Tax'));
    $note = $block->escapeHtml(__('Enter your billing address to get a tax estimate.'));
}
?>

<div id="block-shipping"
    class="block shipping"
    data-mage-init-off='{"collapsible":{"openedState": "active", "saveState": true}}'>
    <div class="title" data-role="title">
        <strong id="block-shipping-heading" role="heading" aria-level="2"><?= $title ?></strong>
    </div>
    <div id="block-summary" class="content" data-role="content" aria-labelledby="block-shipping-heading">
        <form method="post" id="shipping-zip-form">
            <fieldset class="fieldset estimate">
                <legend class="legend">
                    <span><?= $title ?></span>
                </legend>
                <p class="field note"><?= $note ?></p>

                <div class="field">
                    <label class="label" for="estimate_country"><span><?= __('Country') ?></span></label>
                    <div class="control">
                        <select class="select" name="country_id" id="estimate_country"
                            data-bind="value: countryId,
                                       options: availableCountries,
                                       optionsText: 'label',
                                       optionsValue: 'value'"></select>
                    </div>
                </div>
                <div class="field" data-bind="visible: availableRegions().length" style="display:none">
                    <label class="label" for="estimate_region_id"><span><?= __('State/Province') ?></span></label>
                    <div class="control">
                        <select class="select" name="region_id" id="estimate_region_id"
                            data-bind="value: regionId,
                                       options: availableRegions,
                                       optionsText: 'label',
                                       optionsValue: 'value'"></select>
                    </div>
                </div>
                <div class="field" data-bind="visible: !availableRegions().length">
                    <label class="label" for="estimate_region"><span><?= __('State/Province') ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" name="region" id="estimate_region" data-bind="value: region"/>
                    </div>
                </div>
                <div class="field">
                    <label class="label" for="estimate_postcode"><span><?= __('Zip/Postal Code') ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" name="postcode" id="estimate_postcode" data-bind="value: postcode"/>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <script type="text/x-magento-init">
        {
            "#block-summary": {
                "Swissup_Breeze/js/components/estimate-shipping": {}
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>;
        window.customerData = window.checkoutConfig.customerData;
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    </script>
</div>
